export type AircraftCategory =
  | "Light Jet"
  | "Midsize Jet"
  | "Heavy Jet"
  | "Ultra-Long-Range"
  | "VIP Airliner"
  | "Helicopter";

export interface Aircraft {
  id: string;
  slug: string;
  name: string;
  manufacturer: string;
  category: AircraftCategory;
  tagline: string;
  image: string;
  gallery: { label: string; image: string }[];
  passengers: number;
  range: number; // nautical miles
  cruiseSpeed: number; // knots
  cabinLength: number; // feet
  cabinWidth: number; // feet
  cabinHeight: number; // feet
  baggageCapacity: number; // cubic feet
  hourlyRate: number; // USD
  amenities: string[];
  description: string;
  available: boolean;
}

export const aircraftFleet: Aircraft[] = [
  {
    id: "1",
    slug: "embraer-phenom-300e",
    name: "Embraer Phenom 300E",
    manufacturer: "Embraer",
    category: "Light Jet",
    tagline: "The best-selling light jet, built for short-notice regional travel.",
    image: "/images/aircraft/phenom-300e.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/phenom-300e.jpg" }],
    passengers: 8,
    range: 2010,
    cruiseSpeed: 453,
    cabinLength: 17.2,
    cabinWidth: 5.1,
    cabinHeight: 4.9,
    baggageCapacity: 84,
    hourlyRate: 3100,
    amenities: ["Wi-Fi", "Refreshment center", "Quiet cabin", "Forward baggage access"],
    description:
      "A fast, efficient light jet suited to regional legs, with a cabin that comfortably outperforms its class.",
    available: true,
  },
  {
    id: "2",
    slug: "embraer-legacy-500",
    name: "Embraer Legacy 500",
    manufacturer: "Embraer",
    category: "Midsize Jet",
    tagline: "Fly-by-wire precision in a flat-floor, stand-up cabin.",
    image: "/images/aircraft/legacy-500.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/legacy-500.jpg" }],
    passengers: 9,
    range: 3125,
    cruiseSpeed: 466,
    cabinLength: 24.5,
    cabinWidth: 6.7,
    cabinHeight: 6.0,
    baggageCapacity: 130,
    hourlyRate: 4400,
    amenities: ["Wi-Fi", "Fly-by-wire controls", "Flat floor cabin", "Full galley"],
    description:
      "One of the few midsize jets with fly-by-wire controls, paired with a flat-floor cabin built for stand-up comfort.",
    available: true,
  },
  {
    id: "3",
    slug: "gulfstream-g450",
    name: "Gulfstream G450",
    manufacturer: "Gulfstream",
    category: "Midsize Jet",
    tagline: "A proven cabin, refined over two decades of service.",
    image: "/images/aircraft/g450.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/g450.jpg" }],
    passengers: 14,
    range: 4350,
    cruiseSpeed: 476,
    cabinLength: 41.6,
    cabinWidth: 7.3,
    cabinHeight: 6.2,
    baggageCapacity: 169,
    hourlyRate: 5800,
    amenities: ["Wi-Fi", "Forward and aft lavatories", "Full galley", "Multiple cabin zones"],
    description:
      "A dependable long-serving Gulfstream with a spacious cabin and the range to connect most regional business routes.",
    available: true,
  },
  {
    id: "4",
    slug: "dassault-falcon-8x",
    name: "Dassault Falcon 8X",
    manufacturer: "Dassault",
    category: "Heavy Jet",
    tagline: "Three engines, exceptional short-field performance.",
    image: "/images/aircraft/falcon-8x.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/falcon-8x.jpg" }],
    passengers: 16,
    range: 6450,
    cruiseSpeed: 488,
    cabinLength: 42.7,
    cabinWidth: 7.7,
    cabinHeight: 6.2,
    baggageCapacity: 140,
    hourlyRate: 8100,
    amenities: ["Wi-Fi", "Three-engine reliability", "Access to short runways", "Quiet cabin"],
    description:
      "Trijet performance opens up shorter, more challenging runways without giving up ultra-long-range comfort.",
    available: true,
  },
  {
    id: "5",
    slug: "dassault-falcon-900lx",
    name: "Dassault Falcon 900LX",
    manufacturer: "Dassault",
    category: "Heavy Jet",
    tagline: "A widebody-style cabin with three-engine confidence.",
    image: "/images/aircraft/falcon-900lx.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/falcon-900lx.jpg" }],
    passengers: 14,
    range: 4750,
    cruiseSpeed: 459,
    cabinLength: 33.2,
    cabinWidth: 7.7,
    cabinHeight: 6.2,
    baggageCapacity: 127,
    hourlyRate: 7200,
    amenities: ["Wi-Fi", "Three-zone cabin", "Full galley", "Trijet reliability"],
    description:
      "A long-standing favorite for its combination of cabin comfort, range and access to demanding airports.",
    available: true,
  },
  {
    id: "6",
    slug: "gulfstream-g550",
    name: "Gulfstream G550",
    manufacturer: "Gulfstream",
    category: "Heavy Jet",
    tagline: "The long-range benchmark that defined a generation.",
    image: "/images/aircraft/g550.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/g550.jpg" }],
    passengers: 16,
    range: 6750,
    cruiseSpeed: 488,
    cabinLength: 46.8,
    cabinWidth: 7.3,
    cabinHeight: 6.2,
    baggageCapacity: 226,
    hourlyRate: 8600,
    amenities: ["Wi-Fi", "Private aft cabin", "Full galley", "Long-range comfort"],
    description:
      "A long-range favorite among heads of state and executives alike, prized for its range and cabin refinement.",
    available: true,
  },
  {
    id: "7",
    slug: "gulfstream-g650er",
    name: "Gulfstream G650ER",
    manufacturer: "Gulfstream",
    category: "Ultra-Long-Range",
    tagline: "Extended range, in a cabin built to erase time zones.",
    image: "/images/aircraft/g650er.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/g650er.jpg" }],
    passengers: 19,
    range: 7500,
    cruiseSpeed: 516,
    cabinLength: 46.8,
    cabinWidth: 8.5,
    cabinHeight: 6.2,
    baggageCapacity: 195,
    hourlyRate: 9500,
    amenities: ["Wi-Fi", "Private bedroom", "Full galley", "Flat-bed seating", "Extended range tanks"],
    description:
      "The extended-range variant of the G650, connecting continents with cabin altitude and comfort tuned for rest.",
    available: true,
  },
  {
    id: "8",
    slug: "boeing-777-vvip",
    name: "Boeing 777-300ER VVIP",
    manufacturer: "Boeing",
    category: "VIP Airliner",
    tagline: "A private residence, sized for a full delegation.",
    image: "/images/aircraft/boeing-777-vvip.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/boeing-777-vvip.jpg" }],
    passengers: 40,
    range: 7370,
    cruiseSpeed: 490,
    cabinLength: 202.0,
    cabinWidth: 19.5,
    cabinHeight: 8.5,
    baggageCapacity: 2500,
    hourlyRate: 22000,
    amenities: ["Wi-Fi", "Private suite", "Dining room", "Office", "Crew rest quarters"],
    description:
      "A fully customized widebody airframe with intercontinental range, built for heads of state and large delegations.",
    available: true,
  },
  {
    id: "9",
    slug: "boeing-757-vvip",
    name: "Boeing 757 VVIP",
    manufacturer: "Boeing",
    category: "VIP Airliner",
    tagline: "Narrowbody range with widebody-scale living space.",
    image: "/images/aircraft/boeing-757-vvip.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/boeing-757-vvip.jpg" }],
    passengers: 34,
    range: 3900,
    cruiseSpeed: 460,
    cabinLength: 118.0,
    cabinWidth: 11.7,
    cabinHeight: 7.2,
    baggageCapacity: 1790,
    hourlyRate: 16500,
    amenities: ["Wi-Fi", "Private suite", "Full galley", "Conference area", "Crew rest quarters"],
    description:
      "A converted narrowbody airliner reconfigured for full-group travel, with the range for intercontinental legs.",
    available: false,
  },
  {
    id: "10",
    slug: "airbus-h160-signature",
    name: "Airbus H160 Signature",
    manufacturer: "Airbus Helicopters",
    category: "Helicopter",
    tagline: "The most distinctive silhouette in the sky, finished bespoke.",
    image: "/images/aircraft/h160-custom.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/h160-custom.jpg" }],
    passengers: 8,
    range: 480,
    cruiseSpeed: 160,
    cabinLength: 8.5,
    cabinWidth: 6.2,
    cabinHeight: 4.6,
    baggageCapacity: 55,
    hourlyRate: 4200,
    amenities: ["Bespoke cabin finish", "Noise-reducing Blue Edge blades", "Executive seating"],
    description:
      "Airbus's newest-generation helicopter, distinguished by its inclined tail fin and Blue Edge rotor blades, finished in a bespoke livery.",
    available: true,
  },
  {
    id: "11",
    slug: "agustawestland-aw139",
    name: "AgustaWestland AW139",
    manufacturer: "Leonardo",
    category: "Helicopter",
    tagline: "The workhorse of executive and offshore transport.",
    image: "/images/aircraft/aw139.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/aw139.jpg" }],
    passengers: 12,
    range: 573,
    cruiseSpeed: 165,
    cabinLength: 9.1,
    cabinWidth: 6.1,
    cabinHeight: 4.6,
    baggageCapacity: 64,
    hourlyRate: 3800,
    amenities: ["Twin-engine reliability", "Spacious cabin", "Executive configuration available"],
    description:
      "One of the most widely trusted medium twins in executive aviation, valued for cabin space and reliability.",
    available: true,
  },
  {
    id: "12",
    slug: "agustawestland-aw101",
    name: "AgustaWestland AW101",
    manufacturer: "Leonardo",
    category: "Helicopter",
    tagline: "Three-engine capability, finished to VVIP standard.",
    image: "/images/aircraft/aw101.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/aw101.jpg" }],
    passengers: 16,
    range: 750,
    cruiseSpeed: 150,
    cabinLength: 21.2,
    cabinWidth: 6.2,
    cabinHeight: 5.8,
    baggageCapacity: 90,
    hourlyRate: 6500,
    amenities: ["Three-engine redundancy", "VVIP cabin finish", "Extended range tanks"],
    description:
      "A three-engine heavy helicopter used for head-of-state and VVIP transport, finished here to a full VVIP standard.",
    available: true,
  },
  {
    id: "13",
    slug: "airbus-h160",
    name: "Airbus H160",
    manufacturer: "Airbus Helicopters",
    category: "Helicopter",
    tagline: "Efficient, quiet, and unmistakably modern.",
    image: "/images/aircraft/h160.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/h160.jpg" }],
    passengers: 8,
    range: 480,
    cruiseSpeed: 160,
    cabinLength: 8.5,
    cabinWidth: 6.2,
    cabinHeight: 4.6,
    baggageCapacity: 55,
    hourlyRate: 3900,
    amenities: ["Blue Edge rotor blades", "Quiet cabin", "Executive seating"],
    description:
      "Airbus's newest-generation medium twin, built around aerodynamic efficiency and one of the quietest cabins in its class.",
    available: true,
  },
  {
    id: "14",
    slug: "airbus-h155",
    name: "Airbus H155",
    manufacturer: "Airbus Helicopters",
    category: "Helicopter",
    tagline: "A long-serving twin, trusted for VIP transfer.",
    image: "/images/aircraft/h155.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/h155.jpg" }],
    passengers: 8,
    range: 407,
    cruiseSpeed: 150,
    cabinLength: 7.5,
    cabinWidth: 5.6,
    cabinHeight: 4.5,
    baggageCapacity: 46,
    hourlyRate: 3400,
    amenities: ["Twin-engine reliability", "Executive seating", "Low-vibration cabin"],
    description:
      "A refined twin-engine helicopter with a long service record in VIP and corporate transfer work.",
    available: true,
  },
  {
    id: "15",
    slug: "kamov-ka-62",
    name: "Kamov Ka-62",
    manufacturer: "Russian Helicopters",
    category: "Helicopter",
    tagline: "A modern medium twin, built for demanding conditions.",
    image: "/images/aircraft/ka-62.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/ka-62.jpg" }],
    passengers: 15,
    range: 435,
    cruiseSpeed: 149,
    cabinLength: 9.5,
    cabinWidth: 6.0,
    cabinHeight: 4.7,
    baggageCapacity: 60,
    hourlyRate: 3600,
    amenities: ["Composite airframe", "Fenestron tail rotor", "Executive configuration available"],
    description:
      "A modern medium-twin helicopter with a composite airframe and fenestron tail rotor for quieter operation.",
    available: false,
  },
  {
    id: "16",
    slug: "bell-407",
    name: "Bell 407",
    manufacturer: "Bell",
    category: "Helicopter",
    tagline: "Agile, dependable, and ideal for short executive hops.",
    image: "/images/aircraft/bell-407.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/bell-407.jpg" }],
    passengers: 6,
    range: 337,
    cruiseSpeed: 133,
    cabinLength: 6.2,
    cabinWidth: 5.6,
    cabinHeight: 4.3,
    baggageCapacity: 26,
    hourlyRate: 2200,
    amenities: ["Single-engine efficiency", "Rooftop-capable", "Executive seating"],
    description:
      "A single-engine helicopter well suited to short executive transfers and rooftop-to-rooftop travel.",
    available: true,
  },
  {
    id: "17",
    slug: "airbus-h130",
    name: "Airbus H130",
    manufacturer: "Airbus Helicopters",
    category: "Helicopter",
    tagline: "Wide-cabin visibility for scenic and executive transfer.",
    image: "/images/aircraft/h130.jpg",
    gallery: [{ label: "Exterior", image: "/images/aircraft/h130.jpg" }],
    passengers: 7,
    range: 380,
    cruiseSpeed: 140,
    cabinLength: 6.6,
    cabinWidth: 5.9,
    cabinHeight: 4.4,
    baggageCapacity: 30,
    hourlyRate: 2400,
    amenities: ["Wide panoramic cabin", "Single-engine efficiency", "Fenestron tail rotor"],
    description:
      "A single-engine helicopter with an unusually wide, glazed cabin, popular for both scenic and executive transfer work.",
    available: true,
  },
];

export function getAircraftBySlug(slug: string) {
  return aircraftFleet.find((a) => a.slug === slug);
}

export function getAircraftByCategory(category: AircraftCategory | "All") {
  if (category === "All") return aircraftFleet;
  return aircraftFleet.filter((a) => a.category === category);
}

export const aircraftCategories: { name: AircraftCategory; description: string; image: string }[] = [
  {
    name: "Light Jet",
    description: "Perfect for shorter journeys with two or three passengers.",
    image: "/images/aircraft/phenom-300e.jpg",
  },
  {
    name: "Midsize Jet",
    description: "A balance of comfort, range and efficiency for regional travel.",
    image: "/images/aircraft/g450.jpg",
  },
  {
    name: "Heavy Jet",
    description: "Spacious cabins designed for long-distance travel and groups.",
    image: "/images/aircraft/g550.jpg",
  },
  {
    name: "Ultra-Long-Range",
    description: "Maximum range, comfort and privacy for intercontinental legs.",
    image: "/images/aircraft/g650er.jpg",
  },
  {
    name: "VIP Airliner",
    description: "Exceptional space for large groups and residence-level luxury.",
    image: "/images/aircraft/boeing-777-vvip.jpg",
  },
  {
    name: "Helicopter",
    description: "Rooftop-to-runway transfer, and short-hop executive travel.",
    image: "/images/aircraft/h160.jpg",
  },
];
